name: ESLint

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - name: Install
        run: npm ci
      - name: Link
        run: npm run lint
