name: Create draft release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      - '!2.3.*'

jobs:
  build:
    # Need to run on macOS so that the Mac app can be signed (eventually).
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 14
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/electron/twine-*.dmg
            dist/electron/twine-*.exe
            dist/electron/twine-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

