# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(606, 519)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.twStaffs = QtWidgets.QTableWidget(Form)
        self.twStaffs.setGeometry(QtCore.QRect(0, 270, 531, 192))
        self.twStaffs.setObjectName("twStaffs")
        self.twStaffs.setColumnCount(0)
        self.twStaffs.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 215, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.leFio = QtWidgets.QLineEdit(self.layoutWidget)
        self.leFio.setObjectName("leFio")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leFio)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spAge = QtWidgets.QSpinBox(self.layoutWidget)
        self.spAge.setObjectName("spAge")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spAge)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.rbMale = QtWidgets.QRadioButton(self.splitter)
        self.rbMale.setObjectName("rbMale")
        self.radioButton_2 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.splitter)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lePhone = QtWidgets.QLineEdit(self.layoutWidget)
        self.lePhone.setObjectName("lePhone")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lePhone)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.leEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.leEmail.setObjectName("leEmail")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.leEmail)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cbPost = QtWidgets.QComboBox(self.layoutWidget)
        self.cbPost.setObjectName("cbPost")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cbPost)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spExp = QtWidgets.QSpinBox(self.layoutWidget)
        self.spExp.setObjectName("spExp")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spExp)
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(310, 30, 82, 81))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.pbOpen = QtWidgets.QPushButton(self.splitter_2)
        self.pbOpen.setObjectName("pbOpen")
        self.pbInsert = QtWidgets.QPushButton(self.splitter_2)
        self.pbInsert.setObjectName("pbInsert")
        self.pbOpen_3 = QtWidgets.QPushButton(self.splitter_2)
        self.pbOpen_3.setObjectName("pbOpen_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "сотрудники"))
        self.label.setText(_translate("Form", "ФИО:"))
        self.label_2.setText(_translate("Form", "Пол:"))
        self.rbMale.setText(_translate("Form", "муж"))
        self.radioButton_2.setText(_translate("Form", "жен"))
        self.label_3.setText(_translate("Form", "Возраст:"))
        self.label_4.setText(_translate("Form", "Телефон:"))
        self.label_5.setText(_translate("Form", "Почта:"))
        self.label_6.setText(_translate("Form", "Должность:"))
        self.label_7.setText(_translate("Form", "Стаж:"))
        self.pbOpen.setText(_translate("Form", "Открыть"))
        self.pbInsert.setText(_translate("Form", "Добавить"))
        self.pbOpen_3.setText(_translate("Form", "Удалить"))
